
-- EXEMPLO DE LEFT JOIN PARA PEGAR O CLIENTE SEM NOTAS FISCAIS
SELECT C.NOME, COUNT(N.CPF) FROM
CLIENTES AS C LEFT JOIN NOTAS_FISCAIS AS N
ON C.CPF = N.CPF
GROUP BY C.NOME


SELECT C.NOME FROM
CLIENTES AS C LEFT JOIN NOTAS_FISCAIS AS N
ON C.CPF = N.CPF
WHERE N.CPF IS NULL

