/* EXERCÍCIO BANCO: DATABASE MERCADO
- CLIENTE: ID, NOME, CPF, DATA_CAD
- PRODUTO: ID, NOME, PREÇO
- VENDA: ID, ID_CLIENTE, ID_PRODUTO, DATA_VENDA

INSERTS: 3 CLIENTES, 5 PRODUTOS, 6 VENDAS
SELECT: MOSTRAR VENDAS COM NOME DO CLIENTE E NOME DO PRODUTO
*/

CREATE DATABASE MERCADO
USE MERCADO

DROP TABLE CLIENTE
CREATE TABLE CLIENTE(
	ID		INT IDENTITY (1,1) PRIMARY KEY,
	NOME	VARCHAR(70) NOT NULL,
	CPF		VARCHAR(11) NOT NULL UNIQUE,
	DATA_CADASTRO DATETIME NOT NULL DEFAULT GETDATE()
)

DROP TABLE PRODUTO
CREATE TABLE PRODUTO(
	ID INT IDENTITY (1,1) PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	PRECO MONEY NOT NULL
)

DROP TABLE VENDA
CREATE TABLE VENDA(
	ID INT IDENTITY (1,1) PRIMARY KEY,
	CLIENTE_ID INT FOREIGN KEY REFERENCES CLIENTE(ID),
	PRODUTO_ID INT FOREIGN KEY REFERENCES PRODUTO(ID),
	DATA_VENDA DATETIME NOT NULL DEFAULT GETDATE()
)	

SELECT * FROM CLIENTE
SELECT * FROM PRODUTO 
SELECT * FROM VENDA


INSERT CLIENTE (NOME, CPF) 
VALUES
	('Bruno', '11122233344'),
	('Pedro', '11122233355'), 
	('Joao', '11122233366')


INSERT PRODUTO (NOME, PRECO)
VALUES 
	('Banana', 4.90),
	('Sabonete', 8.90),		  
	('Vassoura', 10.90),
	('Prato', 5.90),
    ('Mouse', 59.90)

INSERT VENDA (CLIENTE_ID, PRODUTO_ID)
VALUES
	(1, 1),(2, 1),
	(2, 2),(3,4),
	(3,5)


SELECT C.NOME as Cliente, P.NOME as Produto, P.PRECO as Preço 
FROM VENDA V
JOIN CLIENTE C ON V.CLIENTE_ID = C.ID
JOIN PRODUTO P ON V.PRODUTO_ID = P.ID

SELECT C.NOME as Cliente, SUM(P.PRECO) as PreçoTotal
FROM VENDA V
JOIN CLIENTE C ON V.CLIENTE_ID = C.ID
JOIN PRODUTO P ON V.PRODUTO_ID = P.ID
GROUP BY C.NOME
