CREATE DATABASE LOCADORA
USE LOCADORA

CREATE TABLE CLIENTE(
	ID				INT IDENTITY	(1,1) PRIMARY KEY, 
	NOME_COMPLETO	VARCHAR(100)	NOT NULL,
	CPF				VARCHAR(11)		NOT NULL,
	TELEFONE		VARCHAR(11),
	DATA_NASC		DATE			NOT NULL,
)

CREATE TABLE GENERO(
	ID		INT			IDENTITY (1, 1) PRIMARY KEY,
	GENERO	VARCHAR(50) NOT NULL		UNIQUE,
)

CREATE TABLE CLASSIFICACAO(
	ID		INT IDENTITY	(1, 1)		PRIMARY KEY,
	CLASS	VARCHAR(50)		NOT NULL	UNIQUE,
)

CREATE TABLE FILME(
	ID				INT IDENTITY (1, 1)		PRIMARY KEY, 
	NOME			VARCHAR(60) NOT NULL,
	GENERO			INT			FOREIGN KEY REFERENCES GENERO(ID)			DEFAULT 1, 
	CLASSIFICACAO	INT			FOREIGN KEY REFERENCES CLASSIFICACAO(ID)	DEFAULT 1,
	DATA_LANC		DATE,
	DATA_ADD		DATETIME				DEFAULT GETDATE(),
	PRECO			MONEY		NOT NULL,
	ALUGADO			BIT			NOT NULL	DEFAULT 0
)

CREATE TABLE ESTADO_DEV(
	ID INT IDENTITY (0,1) PRIMARY KEY,
	ESTADO VARCHAR(30) NOT NULL UNIQUE
)

CREATE TABLE ALUGUEL(
	CLIENTE_ID INT FOREIGN KEY REFERENCES CLIENTE(ID),
	FILME_ID INT FOREIGN KEY REFERENCES FILME(ID),
	DATA_ALUGUEL DATETIME DEFAULT GETDATE(),
	DATA_LIMITE DATETIME DEFAULT DATEADD(day, +7, GETDATE()),
	ESTADO_DEVOLUCAO INT FOREIGN KEY REFERENCES ESTADO_DEV(ID) DEFAULT 0
)



SELECT * FROM FILME
SELECT * FROM GENERO
SELECT * FROM CLIENTE
SELECT * FROM CLASSIFICACAO
SELECT * FROM ALUGUEL
SELECT * FROM ESTADO_DEV

INSERT FILME (NOME, GENERO, CLASSIFICACAO, DATA_LANC, PRECO) VALUES ('O Farol', 3, 5,'2019-09-09', 19.99)
INSERT FILME (NOME, GENERO, CLASSIFICACAO, DATA_LANC, PRECO) VALUES ('Velozes e Furiosos', 2, 2,'2019-09-09', 19.99)


SELECT f.NOME AS Nome, g.GENERO AS Gênero, c.CLASS AS Classificação 
FROM FILME f JOIN GENERO g ON g.ID = f.GENERO 
JOIN CLASSIFICACAO c ON c.ID = f.CLASSIFICACAO


