CREATE DATABASE BancoExemplo
USE BancoExemplo

CREATE TABLE CLIENTE(
	ID INT IDENTITY (1,1) PRIMARY KEY,
	NOME_COMPLETO VARCHAR(100) NOT NULL,
	CPF VARCHAR(12) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	DATA_NASC DATE NOT NULL,
	ALTURA NUMERIC (3, 2),
	PESO NUMERIC (3, 2)
)

INSERT INTO CLIENTE (NOME_COMPLETO, CPF, ESTADO, DATA_NASC)
VALUES ('Bruno Oliveira', '11122233344', 'PR', '18/12/2002')

SELECT * FROM CLIENTE
