USE SENAI
GO

CREATE OR ALTER PROC UPDATE_PAGAMENTOS
AS
BEGIN
    UPDATE PAGAMENTOS
    SET SITUACAO = 'em atraso'
    WHERE GETDATE() > VENCIMENTO_BOLETO
    AND SITUACAO = 'pendente'
END


SELECT * FROM PAGAMENTOS
EXEC UPDATE_PAGAMENTOS
SELECT * FROM PAGAMENTOS WHERE SITUACAO = 'em atraso'