USE SENAI
GO 

CREATE OR ALTER TRIGGER AUTO_DISABLE_CURSO
ON CURSO
AFTER UPDATE
AS 
BEGIN
    DECLARE @IS_ATIVO BIT

    SELECT @IS_ATIVO = inserted.ATIVO
    FROM inserted
    JOIN deleted on inserted.ID = deleted.ID

    UPDATE [DISCIPLINAS DO CURSO]
    SET ATIVA = @IS_ATIVO
    FROM inserted ins
    JOIN [DISCIPLINAS DO CURSO] dc ON ins.ID = dc.ID_CURSO
END
GO

CREATE OR ALTER TRIGGER AUTO_DISABLE_DISCI
ON DISCIPLINA
AFTER UPDATE
AS BEGIN
    
    DECLARE @IS_ATIVO BIT

    SELECT @IS_ATIVO = inserted.ATIVO
    FROM inserted
    JOIN deleted on inserted.ID = deleted.ID

    UPDATE [DISCIPLINAS DO CURSO]
    SET ATIVA = @IS_ATIVO
    FROM inserted ins
    JOIN [DISCIPLINAS DO CURSO] dc ON ins.ID = dc.ID_DISCI
END
GO


CREATE OR ALTER TRIGGER AUTO_DISABLE_TURMA
ON [DISCIPLINAS DO CURSO]
AFTER UPDATE
AS 
BEGIN
    DECLARE @IS_ATIVO BIT

    SELECT @IS_ATIVO = inserted.ATIVA
    FROM inserted
    JOIN deleted on inserted.ID = deleted.ID

    UPDATE TURMA
    SET ATIVA = @IS_ATIVO
    FROM inserted ins
    JOIN TURMA t ON ins.ID = t.ID_DISCI_CURSO
END
GO

UPDATE DISCIPLINA
SET ATIVO = 1
WHERE ID = 2
GO

UPDATE [DISCIPLINAS DO CURSO]
SET ATIVA = 1
WHERE ID = 8
GO


SELECT * FROM DISCIPLINA
SELECT * FROM [DISCIPLINAS DO CURSO]
SELECT * FROM TURMA



