USE TESTE_NOTAS_FISCAIS

SELECT * FROM [ITENS NOTAS FISCAIS]

SELECT * FROM FATURAMENTO
INSERT [ITENS NOTAS FISCAIS] (NUMERO, [CODIGO DO PRODUTO], QUANTIDADE, PREÇO)
VALUES (100, 252525, 20, 3.768)
SELECT * FROM FATURAMENTO


SELECT * FROM [TABELA DE PRODUTOS]
SELECT * FROM [ITENS NOTAS FISCAIS]

INSERT INTO [TABELA DE PRODUTOS] ([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], TAMANHO, SABOR, [PREÇO DE LISTA])
VALUES ( 252525, 'Suco Pang', 'Saquinho', '90g', 'Uva', 2.50)

INSERT [ITENS NOTAS FISCAIS] (NUMERO, [CODIGO DO PRODUTO], QUANTIDADE, PREÇO)
VALUES (101, 773912, 30, 25.0)

