CREATE DATABASE EXEMPLO_TRIGGER
GO
USE EXEMPLO_TRIGGER

CREATE TABLE PRODUTO(
    ID INT IDENTITY(1, 1) PRIMARY KEY,
    NOME VARCHAR(60),
    QTD_ESTOQUE INT DEFAULT 0
)

CREATE TABLE VENDAS(
    ID INT IDENTITY(1, 1) PRIMARY KEY,
    QTD INT,
    ID_PROD INT FOREIGN KEY REFERENCES PRODUTO(ID)
)

DELETE FROM VENDAS WHERE ID > 0
DELETE FROM PRODUTO WHERE ID > 0

INSERT PRODUTO (NOME, QTD_ESTOQUE) 
VALUES ('Banana', 5)

SELECT * FROM PRODUTO

INSERT VENDAS (QTD, ID_PROD)
VALUES (2, 3), (3, 4)

INSERT VENDAS (QTD, ID_PROD)
VALUES (3, 4)

SELECT * FROM VENDAS
