USE EXEMPLO_TRIGGER
GO

ALTER TRIGGER UPDATE_STORAGE
ON VENDAS AFTER INSERT
AS BEGIN
    DECLARE @ID INT
    DECLARE @QTD INT


    SELECT @ID = ID_PROD, @QTD = QTD FROM inserted
    
    SELECT * FROM inserted

    UPDATE PRODUTO 
        SET QTD_ESTOQUE = QTD_ESTOQUE - @QTD
        WHERE ID = @ID
END