ALTER PROC GET_QTD_NOTAS (
    @CPF VARCHAR(11),
    @ANO INT,
    @QTD_NOTAS INT OUTPUT,
    @VALOR_GASTO MONEY OUTPUT
) AS BEGIN
    SELECT 
        @QTD_NOTAS = COUNT(*),
        @VALOR_GASTO = SUM(IT.PREÇO * IT.QUANTIDADE)
    FROM [NOTAS FISCAIS] NF JOIN [ITENS NOTAS FISCAIS] IT
    ON NF.NUMERO = IT.NUMERO
    WHERE YEAR(NF.DATA) = @ANO AND
    NF.CPF = @CPF
END