DECLARE @QTD_NOTAS INT, @VALOR_GASTO MONEY

EXEC GET_QTD_NOTAS 
    '1471156710', 
    2015,
    @QTD_NOTAS = @QTD_NOTAS OUTPUT,
    @VALOR_GASTO = @VALOR_GASTO OUTPUT

SELECT @QTD_NOTAS AS [Quantidade de notas], CAST(@VALOR_GASTO AS NUMERIC(12, 2)) AS [Valor Total Gasto]


EXEC [Busca gastos maiores] '1471156710'