CREATE DATABASE ESCOLA_VIRTUAL
GO

USE ESCOLA_VIRTUAL
CREATE TABLE CURSO(
    ID INT IDENTITY(1, 1) PRIMARY KEY,
    NOME VARCHAR(30) NOT NULL,
    VALOR MONEY DEFAULT 200, 
)

CREATE TABLE PROFESSOR(
    ID INT IDENTITY(1, 1) PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL,
    CPF CHAR(11) NOT NULL UNIQUE,
)

CREATE TABLE ALUNO(
    ID INT IDENTITY(1, 1) PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL,
    DT_NASC DATE CHECK (YEAR(DT_NASC) >= 1922),
    CPF CHAR(11) NOT NULL UNIQUE
)

CREATE TABLE TURMA(
    ID INT IDENTITY(1, 1) PRIMARY KEY, 
    ID_CURSO INT FOREIGN KEY REFERENCES CURSO(ID),
    DT_INICIO DATE DEFAULT GETDATE(),
    DT_TERMINO DATE DEFAULT DATEADD(MONTH, 6, GETDATE()),
    ID_PROF INT FOREIGN KEY REFERENCES PROFESSOR(ID),
)

CREATE TABLE INSCRICAO(
    ID INT IDENTITY(1, 1) PRIMARY KEY,
    ID_TURMA INT FOREIGN KEY REFERENCES TURMA(ID),
    ID_ALUNO INT FOREIGN KEY REFERENCES ALUNO(ID)
)

ALTER TABLE ALUNO
ADD ATIVO BIT

ALTER TABLE ALUNO
ADD CONSTRAINT INIT_ATIVO
DEFAULT 1 FOR ATIVO

ALTER TABLE ALUNO
ADD CIDADE VARCHAR(50)

ALTER TABLE PROFESSOR
ADD CIDADE VARCHAR(50)