USE EMPRESA

-- 4
SELECT F.NOME, D.NOME, F.SALARIO 
FROM FUNCIONARIO F
JOIN DEPARTAMENTO D ON F.DEP_ID = D.ID
WHERE F.NOME LIKE 'D%'
ORDER BY F.SALARIO DESC

-- 5
SELECT F.NOME, D.NOME, D.DEP_LOCAL
FROM FUNCIONARIO F
JOIN DEPARTAMENTO D ON D.ID = F.DEP_ID

-- 6

DECLARE @SOMA_SAL MONEY
DECLARE @COUNT_FN INT

SELECT @SOMA_SAL = SUM(SALARIO)
FROM FUNCIONARIO
WHERE LIDER = 'Jonas'

SELECT @COUNT_FN = COUNT(EDV)
FROM FUNCIONARIO
WHERE LIDER != 'Jonas'

DECLARE @EQUAL_DIV MONEY = 0
SELECT @EQUAL_DIV = @SOMA_SAL / @COUNT_FN
SELECT @SOMA_SAL, @COUNT_FN, @EQUAL_DIV

UPDATE FUNCIONARIO
SET SALARIO = SALARIO + @EQUAL_DIV
WHERE LIDER != 'Jonas'

DELETE FROM FUNCIONARIO 
WHERE LIDER = 'Jonas'

SELECT * FROM FUNCIONARIO

-- 7

SELECT F.NOME, F.EDV, F.LIDER, F.SALARIO, G.GRADE_ID 
FROM FUNCIONARIO F
JOIN GRADE_SALARIAL G ON F.SALARIO BETWEEN G.SAL_MIN AND G.SAL_MAX
WHERE DATA_CONTRATACAO < '2010-01-01'


-- 8 

SELECT COUNT(F.EDV) AS QTD_FUNCIONARIOS, D.NOME AS SETOR
FROM FUNCIONARIO F
JOIN DEPARTAMENTO D ON F.DEP_ID = D.ID
WHERE SALARIO > 4000
GROUP BY D.NOME

-- 9 

SELECT NOME, EDV 
FROM FUNCIONARIO
WHERE DATA_CONTRATACAO > '2014-12-31'

-- 10

SELECT AVG(F.SALARIO) AS MEDIA, MAX(SALARIO) AS MAIOR, MIN(F.SALARIO) AS MENOR
FROM FUNCIONARIO F
GROUP BY F.DEP_ID




