CREATE DATABASE EMPRESA
GO

USE EMPRESA

CREATE TABLE DEPARTAMENTO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(20),
    DEP_LOCAL INT,
)

CREATE TABLE FUNCIONARIO (
    EDV INT PRIMARY KEY,
    NOME VARCHAR(25),
    LIDER VARCHAR(25),
    DATA_CONTRATACAO DATE,
    SALARIO MONEY,
    DEP_ID INT FOREIGN KEY REFERENCES DEPARTAMENTO(ID)
)

CREATE TABLE GRADE_SALARIAL (
    GRADE_ID INT IDENTITY(1,1),
    SAL_MIN MONEY,
    SAL_MAX MONEY,
)